### ISSUE TITLE
Redefinition of "Forward"

### ISSUE THREAD

**Issue by bastw055** [Dimencia/DU-Space-Elevator#1]
Hey, thanks a lot for this LUA it's working great.

Just on issue, you redefine "Forward" here:

https://github.com/Dimencia/DU-Space-Elevator/blob/33563db5c9ee9e41f1c07f31a74b6e1b79b5d852/SpaceElevatorShaft.conf#L191

**Comment by Dimencia** [comment]
That... explains a lot.  
Fixing, thx
